---

- name: Get syncthing user info
  ansible.builtin.getent:
    database: passwd
    key: "{{ syncthing_user }}"
  register: __syncthing_user_info

- name: Set user home
  ansible.builtin.set_fact:
    syncthing_home: "{{ __syncthing_user_info['ansible_facts']['getent_passwd'][syncthing_user][4] }}"

- name: Set configuration location
  ansible.builtin.set_fact:
    syncthing_config_file: "{{ syncthing_home }}/.local/state/syncthing/config.xml"

- name: Reset configuration
  when: lookup('env', 'syncthing_reset') | default(False, true) | bool
  block:

    - name: Stop syncthing service
      ansible.builtin.service:
        name: "{{ syncthing_service }}"
        state: stopped
        enabled: false

    - name: Delete configuration
      ansible.builtin.file:
        path: "{{ syncthing_config_file | dirname }}"
        state: absent
      become: yes

    - name: Delete shared folders
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ syncthing_folders }}"
      loop_control:
        label: "{{ item.path }}"

- name: Generate configuration
  ansible.builtin.command:
    cmd: >-
      {{ syncthing_cmd }} generate
  register: __syncthing_generate
  changed_when: __syncthing_generate.stdout is not search('Key exists')
  become: yes
  become_user: "{{ syncthing_user }}"

- name: Start syncthing
  ansible.builtin.service:
    name: "{{ syncthing_service }}"
    state: started
    enabled: yes
  register: __syncthing_service
  become: yes
  when: not syncthing_docker | bool

- name: Wait for 15 seconds  # noqa no-handler
  ansible.builtin.pause:
    seconds: 15
  when: __syncthing_service is changed

- name: Get API key from configuration
  community.general.xml:
    path: "{{ syncthing_config_file }}"
    xpath: /configuration/gui/apikey
    content: text
  register: __syncthing_api_key

- name: Get status using API
  ansible.builtin.uri:
    url: "{{ syncthing_api_url }}/rest/system/status"
    method: GET
    headers:
      X-API-Key: "{{ __syncthing_api_key.matches[0].apikey }}"
    return_content: yes
    validate_certs: false
  register: syncthing_status

- name: Get configuration using API
  ansible.builtin.uri:
    url: "{{ syncthing_api_url }}/rest/system/config"
    method: GET
    headers:
      X-API-Key: "{{ __syncthing_api_key.matches[0].apikey }}"
    return_content: yes
    validate_certs: false
  register: syncthing_config

- name: Show status
  ansible.builtin.debug:
    msg:
      status: "{{ syncthing_status.json }}"
      config: "{{ syncthing_config.json }}"
    verbosity: 1
