---

- name: Variables
  ansible.builtin.include_tasks: vars.yml

- name: Install phase
  ansible.builtin.include_tasks: install.yml

- name: Config phase 1
  ansible.builtin.include_tasks: config-phase1.yml

- name: Config phase 2
  when: not syncthing_install_only | bool
  block:

    - name: Phase 2
      ansible.builtin.include_tasks: config-phase2.yml

    - name: Api phase
      ansible.builtin.include_tasks: api.yml
      vars:
        api_patch: "{{ syncthing_gui_patch }}"

    - name: Copy script for getting config from API
      ansible.builtin.template:
        src: templates/get-config.sh.j2
        dest: /root/syncthing-get-config.sh
        mode: "0700"

    - name: Devices
      ansible.builtin.include_tasks: devices.yml

    - name: Folders
      ansible.builtin.include_tasks: folders.yml
